sudo: required
dist: trusty
install:
    - sudo add-apt-repository -y ppa:jonathonf/texlive-2016 && sudo apt update
    - sudo apt install -y texlive-latex-extra 
script:
    - xelatex CV.latex --halt-on-error
